[global]
	server role = standalone server
	usershare allow guests = yes
	hosts allow = 192.168.0.0/16
	hosts deny = 0.0.0.0/0

[Anime]
	comment = Anime share
	path = /home/micheal/Media/HDD/Anime
	read only = yes
	guest ok = yes
	force user = micheal
	force group = micheal

[Movies]
	comment = Movies share
	path = /home/micheal/Media/HDD/Media/Movies
	read only = yes
	guest ok = yes
	force user = micheal
	force group = micheal
