require("user.vim-settings")
require("user.vim-keybinds")
require("user.plugins")
require("user.colors")
require("user.lualine")
require("user.nvim-tree")
require("user.indent-blankline")
require("user.barbar")
require("user.tree")
require("user.comment")
require("user.treesitter")
require("user.language-servers")
-- require("user.lspsaga")
require("user.cmp")
